common:
  training:
    p_uncond: 0.2
    chkpt_path: ./checkpoints/2023-12-13/run_2556lzwg/checkpoint.pth

dataset:
  name: CIFAR10  # FashionMNIST, CIFAR10, CelebA
  root_dir: ./data  # relative to cwd
  batch_size: 32
  num_workers: 0

model:
  min_channels: 64
  depths: [2, 2]
  # resolutions: 32 -> 16. 4 in the bridge.
  # channels: 64 -> 128. 256 in the bridge.
  # bridge has the same 'depth' as depths[-1].
  # first resolution level, no downsampling.
  cond_channels: 8
  self_attentions: [False, False]
  self_attention_bridge: False
  nb_heads: [0, 0]

optim:  # Adam optimizer
  lr: 1e-4