common:
  training:
    chkpt_path: ./checkpoints/2023_11_26/run_mzuvy5u6/checkpoint.pth

dataset:
  name: CelebA
  root_dir: ./data  # relative to cwd
  batch_size: 128
  num_workers: 0

model:
  nb_channels: 64
  depths: [1, 1]  # equiv. to old num_blocks: 4
  cond_channels: 8
  self_attentions: [False, False]  # equiv. to old start_self_attention: 2
  # Bridge always has self attention for the moment
