common:
  nb_epochs: 100
  training:
    p_uncond: 0.2
    chkpt_path: ./checkpoints/2023-12-14/run_xa2po595/checkpoint.pth

dataset:
  name: CelebA  # FashionMNIST, CIFAR10, CelebA
  root_dir: ./data  # relative to cwd
  batch_size: 32
  num_workers: 0

model:
  min_channels: 64
  depths: [2, 2, 2, 2]
  # resolutions: 128 -> 64 -> 32 -> 16. 4 in the bridge.
  # channels: 64 -> 128 -> 256 -> 512. 1024 in the bridge.
  # bridge has the same 'depth' as depths[-1].
  # first resolution level, no downsampling.
  cond_channels: 8
  self_attentions: [False, False, False, True]
  self_attention_bridge: True
  nb_heads: [0, 0, 0, 4]
