wandb:
  project: diffusion
  mode: online

wandb_watch: True  # log more info

common:
  nb_epochs: 10
  sampling:
    save_path: ./images/samples.png

dataset:
  name: FashionMNIST
  root_dir: ../data  # relative to src directory
  batch_size: 32
  num_workers: 0

diffusion:
  sigma_min: 2e-3
  sigma_max: 80

model:
  nb_channels: 64  # resnet channels
  num_blocks: 6    # resnet blocks
  cond_channels: 2

optim:  # Adam optimizer
  lr: 1e-4
